------------ Magnitude Analysis -------------
-- Find total customers by country
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

-- Find the total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender;

-- Find the total customers by category
SELECT
p.category,
COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales AS f
RIGHT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.category;

-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- What is the average costs in each category
SELECT category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the toal revenue generated by each category
SELECT 
category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products as p
ON f.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer
SELECT 
c.customer_key, c.first_name, c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of items sold across countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


